
version: 2.11.1.{build}

branches:
  only:
    - master

max_jobs: 1

image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

clone_depth: 1

hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

platform: x64

configuration: Release

install:
  - git submodule update --init

build_script:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64;C:\Program Files\Git\usr\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - rm "C:\Program Files\Git\usr\bin\link.exe" # messes with msvc link.exe

  - SET MKN_CL_PREFERRED=1 # forces mkn to use cl even if gcc/clang are found
  - SET MKN_COMPILE_THREADS=1 # mkn use 1 thread heap space issue
  - SET KLOG=3

  - bash -c "PATH=\"/c/Program Files/Git/usr/bin:$PATH\"; mkdir ../google && mv * ../google"

  - git clone https://github.com/mkn/google.sparsehash -b master --depth 1 mkn
  - bash -c "PATH=\"/c/Program Files/Git/usr/bin:$PATH\"; mv mkn/* . && rm -rf mkn && mv ../google ."

  - curl -o mkn.tar -L https://ci.appveyor.com/api/buildjobs/bdexxue25l58r0b1/artifacts/mkn.tar
  - bash -c "PATH=\"/c/Program Files/Git/usr/bin:$PATH\"; tar xf mkn.tar"
  - cp win/master/mkn.exe .

  - bash -c "PATH=\"/c/Program Files/Git/usr/bin:$PATH\"; ./mkn build -a \"-bigobj -D_SPARSEHASH_CI_TESTING_\" -Og 0 -dp test run"
  - bash -c "PATH=\"/c/Program Files/Git/usr/bin:$PATH\"; ./mkn build -a \"-bigobj -D_SPARSEHASH_CI_TESTING_\" -Og 0 -dp bench run"
